### ISSUE TITLE
NoClassDefFoundError when trying to use the extension

### ISSUE THREAD

**Issue by mattogodoy** [nikolaikopernik/code-complexity-plugin#1]
First of all, I love the idea of the extension! Thanks for creating it :)

I installed it in ItelliJ Idea 2023.1.2 (Ultimate Edition) - Build #IU-231.9011.34, built on May 16, 2023
After installing it the IDE requests to be restarted, but when I do I get the following error:

```
java.lang.NoClassDefFoundError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at com.intellij.util.ConcurrencyUtil.manifestExceptionsIn(ConcurrencyUtil.java:271)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$20(DaemonCodeAnalyzerImpl.java:1030)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: com/jetbrains/python/PythonLanguage
	at com.github.nikolaikopernik.codecomplexity.ui.ComplexityInlayHintsProviderKt.<clinit>(ComplexityInlayHintsProvider.kt:20)
	at com.github.nikolaikopernik.codecomplexity.ui.ComplexityInlayHintsProvider.isLanguageSupported(ComplexityInlayHintsProvider.kt:42)
	at com.intellij.codeInsight.hints.HintUtils.getHintProvidersForLanguage(HintUtils.kt:22)
	at com.intellij.codeInsight.hints.InlayHintsPassFactory$Companion.getProviders(InlayHintsPassFactory.kt:98)
	at com.intellij.codeInsight.hints.InlayHintsPassFactory$Companion.access$getProviders(InlayHintsPassFactory.kt:40)
	at com.intellij.codeInsight.hints.InlayHintsPassFactory.createHighlightingPass(InlayHintsPassFactory.kt:35)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:188)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.java:75)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$23(DaemonCodeAnalyzerImpl.java:1077)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$submitInBackground$24(DaemonCodeAnalyzerImpl.java:1066)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.submitInBackground(DaemonCodeAnalyzerImpl.java:1063)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$19(DaemonCodeAnalyzerImpl.java:1028)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: com.jetbrains.python.PythonLanguage PluginClassLoader(plugin=PluginDescriptor(name=Code Complexity, id=com.github.nikolaikopernik.codecomplexity, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.1/plugins/code-complexity-plugin, version=1.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=415, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more
```

and

```
Unhandled exception in [CoroutineName(com.intellij.internal.statistic.service.fus.collectors.ProjectFUStateUsagesLogger), StandaloneCoroutine{Cancelling}@25c3be89, Dispatchers.Default]

java.lang.NoClassDefFoundError: Could not initialize class com.github.nikolaikopernik.codecomplexity.ui.ComplexityInlayHintsProviderKt
	at com.github.nikolaikopernik.codecomplexity.ui.ComplexityInlayHintsProvider.isLanguageSupported(ComplexityInlayHintsProvider.kt:42)
	at com.intellij.codeInsight.hints.HintUtils.getHintProvidersForLanguage(HintUtils.kt:22)
	at com.intellij.codeInsight.hints.settings.providers.NewInlaySettingsProvider.createModels(NewInlaySettingsProvider.kt:16)
	at com.intellij.codeInsight.hints.InlayProviderUsageCollector.getMetrics(InlayProviderUsageCollector.kt:128)
	at com.intellij.internal.statistic.service.fus.collectors.ProjectUsagesCollector.getMetrics(ProjectUsagesCollector.java:83)
	at com.intellij.internal.statistic.service.fus.collectors.ProjectFUStateUsagesLogger$logProjectState$2$1$metrics$1.invoke(FUStateUsagesLogger.kt:258)
	at com.intellij.internal.statistic.service.fus.collectors.ProjectFUStateUsagesLogger$logProjectState$2$1$metrics$1.invoke(FUStateUsagesLogger.kt:258)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
	at com.intellij.internal.statistic.service.fus.collectors.ProjectFUStateUsagesLogger$logProjectState$2$1.invokeSuspend(FUStateUsagesLogger.kt:258)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(com.intellij.internal.statistic.service.fus.collectors.ProjectFUStateUsagesLogger), StandaloneCoroutine{Cancelled}@25c3be89, Dispatchers.Default]
```

Just wanted to let you know.

**Comment by nikolaikopernik** [comment]
Thank you for you effort submitting this issue. Will check it out

**Comment by nikolaikopernik** [comment]
Fixed in afcf45c12d0d2b610219600a60826d6325381ba3 
In a few days, v1.0.1 will be available to use. Until then, you can install the Python plugin as a workaround.

**Comment by mattogodoy** [comment]
That was fast! Thank you :)

**Comment by mattogodoy** [comment]
I just tried the fixed version and it's working! Thank you for that.

I have a question: The paper you linked where Cognitive Complexity is described measures the complexity using points, but your plugin uses a percentage. What does it represent? What is 100%?

**Comment by nikolaikopernik** [comment]
Yes, you are right. The score calculates with points. I just thought it was not enough to show the original points. So I choose `8 points` as a medium complexity method and now it's `100%` meaning all the methods above 100 would be nice to split/improve.

**Comment by mattogodoy** [comment]
Thank you! It's clear now :)
I created 2 PRs for you:

- https://github.com/nikolaikopernik/code-complexity-plugin/pull/2
- https://github.com/nikolaikopernik/code-complexity-plugin/pull/3

Please, ignore them if you don't like them.

**Comment by nikolaikopernik** [comment]
Hmm, I will probably tackle it via configuration - so it will be up to the user to configure if he wants to see the percentages or the original points

**Comment by mattogodoy** [comment]
Okay! Makes sense :)
